yarn 2 needs additional installation configuration (#307)
Without this, the types do not work and you get errors like:

```
error TS2353: Object literal may only specify known properties, and 'websocket' does not exist in type 'RouteShorthandOptions<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, RouteGenericInterface, unknown, FastifySchema, FastifyTypeProvider, FastifyBaseLogger>'.
```

Signed-off-by: Zachary Salzbank <zsalzbank@gmail.com>